// File generated by FlutterFire CLI template.
// To connect to your specific Firebase project, run:
//   flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTRCMXyGSeVXN9OMLJo7hYZoxctYFAtlU',
    appId: '1:485376123476:web:c22283fff2577b3f1903c1',
    messagingSenderId: '485376123476',
    projectId: 'stokado-639d8',
    authDomain: 'stokado-639d8.firebaseapp.com',
    storageBucket: 'stokado-639d8.firebasestorage.app',
    measurementId: 'G-SXL0233533',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREFIBDh8hPJtNp_TvGeX9J4Wbjs4qHqU',
    appId: '1:485376123476:android:dcd40fccd0291eb31903c1',
    messagingSenderId: '485376123476',
    projectId: 'stokado-639d8',
    storageBucket: 'stokado-639d8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQD5Dl7KTt0UYizHVq1osyLe6IZ98jT4',
    appId: '1:485376123476:ios:851d8889062d16c41903c1',
    messagingSenderId: '485376123476',
    projectId: 'stokado-639d8',
    storageBucket: 'stokado-639d8.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTRCMXyGSeVXN9OMLJo7hYZoxctYFAtlU',
    appId: '1:485376123476:web:3e2593a27aba92c21903c1',
    messagingSenderId: '485376123476',
    projectId: 'stokado-639d8',
    authDomain: 'stokado-639d8.firebaseapp.com',
    storageBucket: 'stokado-639d8.firebasestorage.app',
    measurementId: 'G-KGPGNW0BMM',
  );
}
